FUNCTION(ADD_GOOGLE_TEST TEST_SOURCE TEST_NAME)

  ADD_EXECUTABLE(${TEST_NAME} ${TEST_SOURCE})
  TARGET_LINK_LIBRARIES(${TEST_NAME} ${GTEST_LIBRARIES})
  ADD_TEST(NAME ${TEST_NAME} COMMAND ${TEST_NAME})

ENDFUNCTION(ADD_GOOGLE_TEST)